version: "3"

services:
  app:
    build:
      args:
        user: todo
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: todo
    container_name: todo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - todo
  db:
    image: mariadb:10.7
    container_name: todo-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    ports:
      - '127.0.0.1:3306:3306'
    networks:
      - todo
  nginx:
    image: nginx:1.23-alpine
    container_name: todo-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - todo

networks:
  todo:
    driver: bridge